INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CHANNELMODEL3 ChannelModel3)

FIND_PATH(
    CHANNELMODEL3_INCLUDE_DIRS
    NAMES ChannelModel3/api.h
    HINTS $ENV{CHANNELMODEL3_DIR}/include
        ${PC_CHANNELMODEL3_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CHANNELMODEL3_LIBRARIES
    NAMES gnuradio-ChannelModel3
    HINTS $ENV{CHANNELMODEL3_DIR}/lib
        ${PC_CHANNELMODEL3_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHANNELMODEL3 DEFAULT_MSG CHANNELMODEL3_LIBRARIES CHANNELMODEL3_INCLUDE_DIRS)
MARK_AS_ADVANCED(CHANNELMODEL3_LIBRARIES CHANNELMODEL3_INCLUDE_DIRS)

